StuSta Wireguard

diff --git a/scripts/i3/vpn b/scripts/i3/vpn
--- a/scripts/i3/vpn
+++ b/scripts/i3/vpn
@@ -1,9 +1,9 @@
 #!/bin/sh
 # handle vpn connections
 
-# exit code:	0 	all fine, (stusta: no state change
-# 		2 	wrong usage
-# 		-1	some error
+# exit code:    0     all fine
+#         2     wrong usage
+#         -1    some error
 
 tum=tum
 stusta=stusta
@@ -11,40 +11,40 @@ connect=connect
 disconnect=disconnect
 usage="Usage: $0 {$connect|$disconnect} {$tum|$stusta}"
 config_path=/home/leo/.config/vpn
-vpn_stusta=/home/leo/scripts/i3/vpn_stusta
+wg=wg1-ssn
 
 case "$2" in
     $tum)
-	case "$1" in
-	    $connect)
-		# connect to tum
-		openconnect --config $config_path/tum asa-cluster.lrz.de < $config_path/tumpwd
-		;;
-	    $disconnect)
-		# disconnect to tum
-		kill -2 $(cat $config_path/tumpid)
-		;;
-	    *)
-        	echo $usage
-	        exit 2
-		;;
-	esac
+    case "$1" in
+        $connect)
+        # connect to tum
+        openconnect --config $config_path/tum asa-cluster.lrz.de < $config_path/tumpwd
+        ;;
+        $disconnect)
+        # disconnect to tum
+        kill -2 $(cat $config_path/tumpid)
+        ;;
+        *)
+            echo $usage
+            exit 2
+        ;;
+    esac
         ;;
     $stusta)
-	case "$1" in
-	    $connect)
-		$vpn_stusta connect
-		exit $?
-		;;
-	    $disconnect)
-		$vpn_stusta disconnect
-		exit $?
-		;;
-	    *)
-        	echo $usage
-	        exit 2
-		;;
-	esac
+    case "$1" in
+        $connect)
+        wg-quick up $wg
+        exit 0
+        ;;
+        $disconnect)
+        wg-quick down $wg
+        exit 0
+        ;;
+        *)
+            echo $usage
+            exit 2
+        ;;
+    esac
         ;;
     *)
         echo $usage
diff --git a/scripts/i3/vpn_info b/scripts/i3/vpn_info
--- a/scripts/i3/vpn_info
+++ b/scripts/i3/vpn_info
@@ -2,28 +2,33 @@
 
 # Gives information which vpn connection is currently active
 
-# exit code:	0 	connected
-#		1	disconnected
-#		2	wrong usage
-#		-1 	error
+# exit code: 0  connected
+#            1  disconnected
+#            2  wrong usage
+#           -1  error
 
 usage="Usage: $0 {tum|stusta}"
 
 case "$1" in
-	stusta)
-		# A ping to daten.stusta.de gives information if the network is reachable
-		ping daten.stusta.de -4 -c1 -W3 | grep "64 bytes"
-		exit $?
-		;;
-	tum)
-		# check if pid file of openconnect is present
-		test -e $HOME/.config/vpn/tumpid
-		exit $?
-		;;
-	*)
-		echo $usage
-		exit 2
-		;;
+    stusta)
+        # A ping to daten.stusta.de gives information if the network is reachable
+        if ping daten.stusta.de -4 -c1 -W3 | grep "64 bytes"
+        then
+            exit 0
+        else
+            ping daten.stusta.de -6 -c1 -W3 | grep "64 bytes"
+            exit $?
+        fi
+        ;;
+    tum)
+        # check if pid file of openconnect is present
+        test -e $HOME/.config/vpn/tumpid
+        exit $?
+        ;;
+    *)
+        echo $usage
+        exit 2
+        ;;
 esac
 
 
